// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageQueue.proto

package com.messageq.api.creation;

public interface ExchangeCreationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExchangeCreationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exchangeName = 1;</code>
   * @return The exchangeName.
   */
  java.lang.String getExchangeName();
  /**
   * <code>string exchangeName = 1;</code>
   * @return The bytes for exchangeName.
   */
  com.google.protobuf.ByteString
      getExchangeNameBytes();
}
