// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionQueue.proto

package com.messageq.api.actions;

public final class ActionQueue {
  private ActionQueue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushMessageConfirmationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushMessageConfirmationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PopMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PopMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueueMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueueMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021actionQueue.proto\032\031google/protobuf/any" +
      ".proto\032\037google/protobuf/timestamp.proto\"" +
      "^\n\022PushMessageRequest\022\024\n\014exchangeName\030\001 " +
      "\001(\t\022\022\n\nroutingKey\030\002 \001(\t\022\036\n\007message\030\003 \001(\013" +
      "2\r.QueueMessage\"^\n\037PushMessageConfirmati" +
      "onResponse\022\014\n\004type\030\001 \001(\t\022-\n\ttimestamp\030\002 " +
      "\001(\0132\032.google.protobuf.Timestamp\"&\n\021PopMe" +
      "ssageRequest\022\021\n\tqueueName\030\001 \001(\t\"C\n\014Queue" +
      "Message\022\014\n\004type\030\001 \001(\t\022%\n\007message\030\002 \001(\0132\024" +
      ".google.protobuf.Any2\224\001\n\027QueueActionsGrp" +
      "cService\022F\n\013PushMessage\022\023.PushMessageReq" +
      "uest\032 .PushMessageConfirmationResponse\"\000" +
      "\0221\n\nPopMessage\022\022.PopMessageRequest\032\r.Que" +
      "ueMessage\"\000B\034\n\030com.messageq.api.actionsP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_PushMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushMessageRequest_descriptor,
        new java.lang.String[] { "ExchangeName", "RoutingKey", "Message", });
    internal_static_PushMessageConfirmationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PushMessageConfirmationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushMessageConfirmationResponse_descriptor,
        new java.lang.String[] { "Type", "Timestamp", });
    internal_static_PopMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PopMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PopMessageRequest_descriptor,
        new java.lang.String[] { "QueueName", });
    internal_static_QueueMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_QueueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueueMessage_descriptor,
        new java.lang.String[] { "Type", "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
