// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionQueue.proto

package com.messageq.api.actions;

public interface PopMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PopMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string queueName = 1;</code>
   * @return The queueName.
   */
  java.lang.String getQueueName();
  /**
   * <code>string queueName = 1;</code>
   * @return The bytes for queueName.
   */
  com.google.protobuf.ByteString
      getQueueNameBytes();

  /**
   * <code>.QueueMessage message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.QueueMessage message = 2;</code>
   * @return The message.
   */
  com.messageq.api.actions.QueueMessage getMessage();
  /**
   * <code>.QueueMessage message = 2;</code>
   */
  com.messageq.api.actions.QueueMessageOrBuilder getMessageOrBuilder();
}
