// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionQueue.proto

package com.messageq.api.actions;

/**
 * Protobuf type {@code PushMessageRequest}
 */
public final class PushMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PushMessageRequest)
    PushMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PushMessageRequest.newBuilder() to construct.
  private PushMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PushMessageRequest() {
    exchangeName_ = "";
    routingKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PushMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PushMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            exchangeName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            routingKey_ = s;
            break;
          }
          case 26: {
            com.messageq.api.actions.QueueMessage.Builder subBuilder = null;
            if (message_ != null) {
              subBuilder = message_.toBuilder();
            }
            message_ = input.readMessage(com.messageq.api.actions.QueueMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(message_);
              message_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.messageq.api.actions.ActionQueue.internal_static_PushMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.messageq.api.actions.ActionQueue.internal_static_PushMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.messageq.api.actions.PushMessageRequest.class, com.messageq.api.actions.PushMessageRequest.Builder.class);
  }

  public static final int EXCHANGENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object exchangeName_;
  /**
   * <code>string exchangeName = 1;</code>
   * @return The exchangeName.
   */
  @java.lang.Override
  public java.lang.String getExchangeName() {
    java.lang.Object ref = exchangeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exchangeName_ = s;
      return s;
    }
  }
  /**
   * <code>string exchangeName = 1;</code>
   * @return The bytes for exchangeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExchangeNameBytes() {
    java.lang.Object ref = exchangeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exchangeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUTINGKEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object routingKey_;
  /**
   * <code>string routingKey = 2;</code>
   * @return The routingKey.
   */
  @java.lang.Override
  public java.lang.String getRoutingKey() {
    java.lang.Object ref = routingKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      routingKey_ = s;
      return s;
    }
  }
  /**
   * <code>string routingKey = 2;</code>
   * @return The bytes for routingKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoutingKeyBytes() {
    java.lang.Object ref = routingKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      routingKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private com.messageq.api.actions.QueueMessage message_;
  /**
   * <code>.QueueMessage message = 3;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return message_ != null;
  }
  /**
   * <code>.QueueMessage message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public com.messageq.api.actions.QueueMessage getMessage() {
    return message_ == null ? com.messageq.api.actions.QueueMessage.getDefaultInstance() : message_;
  }
  /**
   * <code>.QueueMessage message = 3;</code>
   */
  @java.lang.Override
  public com.messageq.api.actions.QueueMessageOrBuilder getMessageOrBuilder() {
    return getMessage();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getExchangeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exchangeName_);
    }
    if (!getRoutingKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, routingKey_);
    }
    if (message_ != null) {
      output.writeMessage(3, getMessage());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getExchangeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exchangeName_);
    }
    if (!getRoutingKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, routingKey_);
    }
    if (message_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMessage());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.messageq.api.actions.PushMessageRequest)) {
      return super.equals(obj);
    }
    com.messageq.api.actions.PushMessageRequest other = (com.messageq.api.actions.PushMessageRequest) obj;

    if (!getExchangeName()
        .equals(other.getExchangeName())) return false;
    if (!getRoutingKey()
        .equals(other.getRoutingKey())) return false;
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXCHANGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getExchangeName().hashCode();
    hash = (37 * hash) + ROUTINGKEY_FIELD_NUMBER;
    hash = (53 * hash) + getRoutingKey().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messageq.api.actions.PushMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.messageq.api.actions.PushMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messageq.api.actions.PushMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.messageq.api.actions.PushMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PushMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PushMessageRequest)
      com.messageq.api.actions.PushMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messageq.api.actions.ActionQueue.internal_static_PushMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messageq.api.actions.ActionQueue.internal_static_PushMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messageq.api.actions.PushMessageRequest.class, com.messageq.api.actions.PushMessageRequest.Builder.class);
    }

    // Construct using com.messageq.api.actions.PushMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exchangeName_ = "";

      routingKey_ = "";

      if (messageBuilder_ == null) {
        message_ = null;
      } else {
        message_ = null;
        messageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.messageq.api.actions.ActionQueue.internal_static_PushMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.messageq.api.actions.PushMessageRequest getDefaultInstanceForType() {
      return com.messageq.api.actions.PushMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.messageq.api.actions.PushMessageRequest build() {
      com.messageq.api.actions.PushMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.messageq.api.actions.PushMessageRequest buildPartial() {
      com.messageq.api.actions.PushMessageRequest result = new com.messageq.api.actions.PushMessageRequest(this);
      result.exchangeName_ = exchangeName_;
      result.routingKey_ = routingKey_;
      if (messageBuilder_ == null) {
        result.message_ = message_;
      } else {
        result.message_ = messageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.messageq.api.actions.PushMessageRequest) {
        return mergeFrom((com.messageq.api.actions.PushMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.messageq.api.actions.PushMessageRequest other) {
      if (other == com.messageq.api.actions.PushMessageRequest.getDefaultInstance()) return this;
      if (!other.getExchangeName().isEmpty()) {
        exchangeName_ = other.exchangeName_;
        onChanged();
      }
      if (!other.getRoutingKey().isEmpty()) {
        routingKey_ = other.routingKey_;
        onChanged();
      }
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.messageq.api.actions.PushMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.messageq.api.actions.PushMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object exchangeName_ = "";
    /**
     * <code>string exchangeName = 1;</code>
     * @return The exchangeName.
     */
    public java.lang.String getExchangeName() {
      java.lang.Object ref = exchangeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @return The bytes for exchangeName.
     */
    public com.google.protobuf.ByteString
        getExchangeNameBytes() {
      java.lang.Object ref = exchangeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @param value The exchangeName to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exchangeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExchangeName() {
      
      exchangeName_ = getDefaultInstance().getExchangeName();
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @param value The bytes for exchangeName to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exchangeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object routingKey_ = "";
    /**
     * <code>string routingKey = 2;</code>
     * @return The routingKey.
     */
    public java.lang.String getRoutingKey() {
      java.lang.Object ref = routingKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routingKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string routingKey = 2;</code>
     * @return The bytes for routingKey.
     */
    public com.google.protobuf.ByteString
        getRoutingKeyBytes() {
      java.lang.Object ref = routingKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routingKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string routingKey = 2;</code>
     * @param value The routingKey to set.
     * @return This builder for chaining.
     */
    public Builder setRoutingKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      routingKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string routingKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoutingKey() {
      
      routingKey_ = getDefaultInstance().getRoutingKey();
      onChanged();
      return this;
    }
    /**
     * <code>string routingKey = 2;</code>
     * @param value The bytes for routingKey to set.
     * @return This builder for chaining.
     */
    public Builder setRoutingKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      routingKey_ = value;
      onChanged();
      return this;
    }

    private com.messageq.api.actions.QueueMessage message_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.messageq.api.actions.QueueMessage, com.messageq.api.actions.QueueMessage.Builder, com.messageq.api.actions.QueueMessageOrBuilder> messageBuilder_;
    /**
     * <code>.QueueMessage message = 3;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return messageBuilder_ != null || message_ != null;
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     * @return The message.
     */
    public com.messageq.api.actions.QueueMessage getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? com.messageq.api.actions.QueueMessage.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    public Builder setMessage(com.messageq.api.actions.QueueMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    public Builder setMessage(
        com.messageq.api.actions.QueueMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    public Builder mergeMessage(com.messageq.api.actions.QueueMessage value) {
      if (messageBuilder_ == null) {
        if (message_ != null) {
          message_ =
            com.messageq.api.actions.QueueMessage.newBuilder(message_).mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        messageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        message_ = null;
        onChanged();
      } else {
        message_ = null;
        messageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    public com.messageq.api.actions.QueueMessage.Builder getMessageBuilder() {
      
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    public com.messageq.api.actions.QueueMessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            com.messageq.api.actions.QueueMessage.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.QueueMessage message = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.messageq.api.actions.QueueMessage, com.messageq.api.actions.QueueMessage.Builder, com.messageq.api.actions.QueueMessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.messageq.api.actions.QueueMessage, com.messageq.api.actions.QueueMessage.Builder, com.messageq.api.actions.QueueMessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PushMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:PushMessageRequest)
  private static final com.messageq.api.actions.PushMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.messageq.api.actions.PushMessageRequest();
  }

  public static com.messageq.api.actions.PushMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PushMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<PushMessageRequest>() {
    @java.lang.Override
    public PushMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PushMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PushMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PushMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.messageq.api.actions.PushMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

