// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionQueue.proto

package com.messageq.api.actions;

public interface PushMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PushMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exchangeName = 1;</code>
   * @return The exchangeName.
   */
  java.lang.String getExchangeName();
  /**
   * <code>string exchangeName = 1;</code>
   * @return The bytes for exchangeName.
   */
  com.google.protobuf.ByteString
      getExchangeNameBytes();

  /**
   * <code>string routingKey = 2;</code>
   * @return The routingKey.
   */
  java.lang.String getRoutingKey();
  /**
   * <code>string routingKey = 2;</code>
   * @return The bytes for routingKey.
   */
  com.google.protobuf.ByteString
      getRoutingKeyBytes();

  /**
   * <code>.QueueMessage message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.QueueMessage message = 3;</code>
   * @return The message.
   */
  com.messageq.api.actions.QueueMessage getMessage();
  /**
   * <code>.QueueMessage message = 3;</code>
   */
  com.messageq.api.actions.QueueMessageOrBuilder getMessageOrBuilder();
}
