// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionQueue.proto

package com.messageq.api.actions;

public interface QueueMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueueMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.google.protobuf.Any message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.google.protobuf.Any message = 2;</code>
   * @return The message.
   */
  com.google.protobuf.Any getMessage();
  /**
   * <code>.google.protobuf.Any message = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getMessageOrBuilder();
}
