// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionQueue.proto

package com.messageq.api.actions;

public interface QueueMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueueMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.google.protobuf.Any payload = 2;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>.google.protobuf.Any payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.Any getPayload();
  /**
   * <code>.google.protobuf.Any payload = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getPayloadOrBuilder();
}
