// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageQueue.proto

package com.messageq.config;

/**
 * Protobuf type {@code CreatePlayerQueueRequest}
 */
public final class CreatePlayerQueueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreatePlayerQueueRequest)
    CreatePlayerQueueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatePlayerQueueRequest.newBuilder() to construct.
  private CreatePlayerQueueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatePlayerQueueRequest() {
    exchangeName_ = "";
    queueName_ = "";
    routingKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreatePlayerQueueRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreatePlayerQueueRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            exchangeName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            queueName_ = s;
            break;
          }
          case 24: {

            playerId_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            routingKey_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.messageq.config.ManageQueue.internal_static_CreatePlayerQueueRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.messageq.config.ManageQueue.internal_static_CreatePlayerQueueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.messageq.config.CreatePlayerQueueRequest.class, com.messageq.config.CreatePlayerQueueRequest.Builder.class);
  }

  public static final int EXCHANGENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object exchangeName_;
  /**
   * <code>string exchangeName = 1;</code>
   * @return The exchangeName.
   */
  @java.lang.Override
  public java.lang.String getExchangeName() {
    java.lang.Object ref = exchangeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exchangeName_ = s;
      return s;
    }
  }
  /**
   * <code>string exchangeName = 1;</code>
   * @return The bytes for exchangeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExchangeNameBytes() {
    java.lang.Object ref = exchangeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exchangeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUEUENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object queueName_;
  /**
   * <code>string queueName = 2;</code>
   * @return The queueName.
   */
  @java.lang.Override
  public java.lang.String getQueueName() {
    java.lang.Object ref = queueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queueName_ = s;
      return s;
    }
  }
  /**
   * <code>string queueName = 2;</code>
   * @return The bytes for queueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueueNameBytes() {
    java.lang.Object ref = queueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYERID_FIELD_NUMBER = 3;
  private int playerId_;
  /**
   * <code>int32 playerId = 3;</code>
   * @return The playerId.
   */
  @java.lang.Override
  public int getPlayerId() {
    return playerId_;
  }

  public static final int ROUTINGKEY_FIELD_NUMBER = 4;
  private volatile java.lang.Object routingKey_;
  /**
   * <code>string routingKey = 4;</code>
   * @return The routingKey.
   */
  @java.lang.Override
  public java.lang.String getRoutingKey() {
    java.lang.Object ref = routingKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      routingKey_ = s;
      return s;
    }
  }
  /**
   * <code>string routingKey = 4;</code>
   * @return The bytes for routingKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoutingKeyBytes() {
    java.lang.Object ref = routingKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      routingKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getExchangeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exchangeName_);
    }
    if (!getQueueNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, queueName_);
    }
    if (playerId_ != 0) {
      output.writeInt32(3, playerId_);
    }
    if (!getRoutingKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, routingKey_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getExchangeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exchangeName_);
    }
    if (!getQueueNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, queueName_);
    }
    if (playerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, playerId_);
    }
    if (!getRoutingKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, routingKey_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.messageq.config.CreatePlayerQueueRequest)) {
      return super.equals(obj);
    }
    com.messageq.config.CreatePlayerQueueRequest other = (com.messageq.config.CreatePlayerQueueRequest) obj;

    if (!getExchangeName()
        .equals(other.getExchangeName())) return false;
    if (!getQueueName()
        .equals(other.getQueueName())) return false;
    if (getPlayerId()
        != other.getPlayerId()) return false;
    if (!getRoutingKey()
        .equals(other.getRoutingKey())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXCHANGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getExchangeName().hashCode();
    hash = (37 * hash) + QUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getQueueName().hashCode();
    hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerId();
    hash = (37 * hash) + ROUTINGKEY_FIELD_NUMBER;
    hash = (53 * hash) + getRoutingKey().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messageq.config.CreatePlayerQueueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.messageq.config.CreatePlayerQueueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreatePlayerQueueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreatePlayerQueueRequest)
      com.messageq.config.CreatePlayerQueueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messageq.config.ManageQueue.internal_static_CreatePlayerQueueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messageq.config.ManageQueue.internal_static_CreatePlayerQueueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messageq.config.CreatePlayerQueueRequest.class, com.messageq.config.CreatePlayerQueueRequest.Builder.class);
    }

    // Construct using com.messageq.config.CreatePlayerQueueRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exchangeName_ = "";

      queueName_ = "";

      playerId_ = 0;

      routingKey_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.messageq.config.ManageQueue.internal_static_CreatePlayerQueueRequest_descriptor;
    }

    @java.lang.Override
    public com.messageq.config.CreatePlayerQueueRequest getDefaultInstanceForType() {
      return com.messageq.config.CreatePlayerQueueRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.messageq.config.CreatePlayerQueueRequest build() {
      com.messageq.config.CreatePlayerQueueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.messageq.config.CreatePlayerQueueRequest buildPartial() {
      com.messageq.config.CreatePlayerQueueRequest result = new com.messageq.config.CreatePlayerQueueRequest(this);
      result.exchangeName_ = exchangeName_;
      result.queueName_ = queueName_;
      result.playerId_ = playerId_;
      result.routingKey_ = routingKey_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.messageq.config.CreatePlayerQueueRequest) {
        return mergeFrom((com.messageq.config.CreatePlayerQueueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.messageq.config.CreatePlayerQueueRequest other) {
      if (other == com.messageq.config.CreatePlayerQueueRequest.getDefaultInstance()) return this;
      if (!other.getExchangeName().isEmpty()) {
        exchangeName_ = other.exchangeName_;
        onChanged();
      }
      if (!other.getQueueName().isEmpty()) {
        queueName_ = other.queueName_;
        onChanged();
      }
      if (other.getPlayerId() != 0) {
        setPlayerId(other.getPlayerId());
      }
      if (!other.getRoutingKey().isEmpty()) {
        routingKey_ = other.routingKey_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.messageq.config.CreatePlayerQueueRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.messageq.config.CreatePlayerQueueRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object exchangeName_ = "";
    /**
     * <code>string exchangeName = 1;</code>
     * @return The exchangeName.
     */
    public java.lang.String getExchangeName() {
      java.lang.Object ref = exchangeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @return The bytes for exchangeName.
     */
    public com.google.protobuf.ByteString
        getExchangeNameBytes() {
      java.lang.Object ref = exchangeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @param value The exchangeName to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exchangeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExchangeName() {
      
      exchangeName_ = getDefaultInstance().getExchangeName();
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeName = 1;</code>
     * @param value The bytes for exchangeName to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exchangeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object queueName_ = "";
    /**
     * <code>string queueName = 2;</code>
     * @return The queueName.
     */
    public java.lang.String getQueueName() {
      java.lang.Object ref = queueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string queueName = 2;</code>
     * @return The bytes for queueName.
     */
    public com.google.protobuf.ByteString
        getQueueNameBytes() {
      java.lang.Object ref = queueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string queueName = 2;</code>
     * @param value The queueName to set.
     * @return This builder for chaining.
     */
    public Builder setQueueName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      queueName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string queueName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueueName() {
      
      queueName_ = getDefaultInstance().getQueueName();
      onChanged();
      return this;
    }
    /**
     * <code>string queueName = 2;</code>
     * @param value The bytes for queueName to set.
     * @return This builder for chaining.
     */
    public Builder setQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      queueName_ = value;
      onChanged();
      return this;
    }

    private int playerId_ ;
    /**
     * <code>int32 playerId = 3;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public int getPlayerId() {
      return playerId_;
    }
    /**
     * <code>int32 playerId = 3;</code>
     * @param value The playerId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerId(int value) {
      
      playerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 playerId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerId() {
      
      playerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object routingKey_ = "";
    /**
     * <code>string routingKey = 4;</code>
     * @return The routingKey.
     */
    public java.lang.String getRoutingKey() {
      java.lang.Object ref = routingKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routingKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string routingKey = 4;</code>
     * @return The bytes for routingKey.
     */
    public com.google.protobuf.ByteString
        getRoutingKeyBytes() {
      java.lang.Object ref = routingKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routingKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string routingKey = 4;</code>
     * @param value The routingKey to set.
     * @return This builder for chaining.
     */
    public Builder setRoutingKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      routingKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string routingKey = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoutingKey() {
      
      routingKey_ = getDefaultInstance().getRoutingKey();
      onChanged();
      return this;
    }
    /**
     * <code>string routingKey = 4;</code>
     * @param value The bytes for routingKey to set.
     * @return This builder for chaining.
     */
    public Builder setRoutingKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      routingKey_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreatePlayerQueueRequest)
  }

  // @@protoc_insertion_point(class_scope:CreatePlayerQueueRequest)
  private static final com.messageq.config.CreatePlayerQueueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.messageq.config.CreatePlayerQueueRequest();
  }

  public static com.messageq.config.CreatePlayerQueueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePlayerQueueRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreatePlayerQueueRequest>() {
    @java.lang.Override
    public CreatePlayerQueueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreatePlayerQueueRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreatePlayerQueueRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePlayerQueueRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.messageq.config.CreatePlayerQueueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

