// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageQueue.proto

package com.messageq.config;

public interface CreatePlayerQueueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePlayerQueueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exchangeName = 1;</code>
   * @return The exchangeName.
   */
  java.lang.String getExchangeName();
  /**
   * <code>string exchangeName = 1;</code>
   * @return The bytes for exchangeName.
   */
  com.google.protobuf.ByteString
      getExchangeNameBytes();

  /**
   * <code>string queueName = 2;</code>
   * @return The queueName.
   */
  java.lang.String getQueueName();
  /**
   * <code>string queueName = 2;</code>
   * @return The bytes for queueName.
   */
  com.google.protobuf.ByteString
      getQueueNameBytes();

  /**
   * <code>int32 playerId = 3;</code>
   * @return The playerId.
   */
  int getPlayerId();
}
