// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageQueue.proto

package com.messageq.config;

public interface CreatePlayerQueueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePlayerQueueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exchangeName = 1;</code>
   * @return The exchangeName.
   */
  java.lang.String getExchangeName();
  /**
   * <code>string exchangeName = 1;</code>
   * @return The bytes for exchangeName.
   */
  com.google.protobuf.ByteString
      getExchangeNameBytes();

  /**
   * <code>string queueName = 2;</code>
   * @return The queueName.
   */
  java.lang.String getQueueName();
  /**
   * <code>string queueName = 2;</code>
   * @return The bytes for queueName.
   */
  com.google.protobuf.ByteString
      getQueueNameBytes();

  /**
   * <code>int32 playerId = 3;</code>
   * @return The playerId.
   */
  int getPlayerId();

  /**
   * <code>bool created = 4;</code>
   * @return The created.
   */
  boolean getCreated();

  /**
   * <code>string errorMessage = 5;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 5;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
