// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: actionQueue.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class QueueActionsGrpcService
{
  static readonly string __ServiceName = "QueueActionsGrpcService";

  static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (message is global::Google.Protobuf.IBufferMessage)
    {
      context.SetPayloadLength(message.CalculateSize());
      global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
      context.Complete();
      return;
    }
    #endif
    context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
  }

  static class __Helper_MessageCache<T>
  {
    public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
  }

  static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (__Helper_MessageCache<T>.IsBufferMessage)
    {
      return parser.ParseFrom(context.PayloadAsReadOnlySequence());
    }
    #endif
    return parser.ParseFrom(context.PayloadAsNewBuffer());
  }

  static readonly grpc::Marshaller<global::PushMessageRequest> __Marshaller_PushMessageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PushMessageRequest.Parser));
  static readonly grpc::Marshaller<global::PushMessageConfirmationResponse> __Marshaller_PushMessageConfirmationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PushMessageConfirmationResponse.Parser));
  static readonly grpc::Marshaller<global::PopMessageRequest> __Marshaller_PopMessageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PopMessageRequest.Parser));
  static readonly grpc::Marshaller<global::QueueMessage> __Marshaller_QueueMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::QueueMessage.Parser));

  static readonly grpc::Method<global::PushMessageRequest, global::PushMessageConfirmationResponse> __Method_PushMessage = new grpc::Method<global::PushMessageRequest, global::PushMessageConfirmationResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "PushMessage",
      __Marshaller_PushMessageRequest,
      __Marshaller_PushMessageConfirmationResponse);

  static readonly grpc::Method<global::PopMessageRequest, global::QueueMessage> __Method_PopMessage = new grpc::Method<global::PopMessageRequest, global::QueueMessage>(
      grpc::MethodType.Unary,
      __ServiceName,
      "PopMessage",
      __Marshaller_PopMessageRequest,
      __Marshaller_QueueMessage);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::ActionQueueReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of QueueActionsGrpcService</summary>
  [grpc::BindServiceMethod(typeof(QueueActionsGrpcService), "BindService")]
  public abstract partial class QueueActionsGrpcServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::PushMessageConfirmationResponse> PushMessage(global::PushMessageRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::QueueMessage> PopMessage(global::PopMessageRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for QueueActionsGrpcService</summary>
  public partial class QueueActionsGrpcServiceClient : grpc::ClientBase<QueueActionsGrpcServiceClient>
  {
    /// <summary>Creates a new client for QueueActionsGrpcService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public QueueActionsGrpcServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for QueueActionsGrpcService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public QueueActionsGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected QueueActionsGrpcServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected QueueActionsGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::PushMessageConfirmationResponse PushMessage(global::PushMessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return PushMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::PushMessageConfirmationResponse PushMessage(global::PushMessageRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_PushMessage, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::PushMessageConfirmationResponse> PushMessageAsync(global::PushMessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return PushMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::PushMessageConfirmationResponse> PushMessageAsync(global::PushMessageRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_PushMessage, null, options, request);
    }
    public virtual global::QueueMessage PopMessage(global::PopMessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return PopMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::QueueMessage PopMessage(global::PopMessageRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_PopMessage, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::QueueMessage> PopMessageAsync(global::PopMessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return PopMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::QueueMessage> PopMessageAsync(global::PopMessageRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_PopMessage, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override QueueActionsGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new QueueActionsGrpcServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(QueueActionsGrpcServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_PushMessage, serviceImpl.PushMessage)
        .AddMethod(__Method_PopMessage, serviceImpl.PopMessage).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, QueueActionsGrpcServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_PushMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PushMessageRequest, global::PushMessageConfirmationResponse>(serviceImpl.PushMessage));
    serviceBinder.AddMethod(__Method_PopMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PopMessageRequest, global::QueueMessage>(serviceImpl.PopMessage));
  }

}
#endregion
