// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: manageQueue.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from manageQueue.proto</summary>
public static partial class ManageQueueReflection {

  #region Descriptor
  /// <summary>File descriptor for manageQueue.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ManageQueueReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFtYW5hZ2VRdWV1ZS5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnBy",
          "b3RvMqYBChZNYW5hZ2VRdWV1ZUdycGNTZXJ2aWNlEkIKDkNyZWF0ZUV4Y2hh",
          "bmdlEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVm",
          "LkVtcHR5IgASSAoUQ29ubmVjdFBsYXllclRvUXVldWUSFi5nb29nbGUucHJv",
          "dG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiAEIlCiFjb20u",
          "aGlteW5hbWVpc2lsbmFuby5tZXNzYWdlcS5hcGlQAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, null));
  }
  #endregion

}

#endregion Designer generated code
